[package]
version = "0.0.2"
authors = [
  "nickray <n@stalder.io>",
]
description = "Peripheral access API for ARM Musca B1 microcontroller"
documentation = "https://docs.rs/muscab1-pac"
keywords = ["no-std", "cortex-m", "arm", "musca", "svd2rust"]
license = "MIT OR Apache-2.0"
name = "muscab1-pac"
repository = "https://github.com/nickray/muscab1-pac"
edition = "2018"

[lib]

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
critical-section = { version = "1", optional = true }
vcell = "0.1"

[features]
rt = ["cortex-m-rt/device"]
