#![doc = "Peripheral access API for MUSCA_B1 microcontrollers (generated using svd2rust v0.36.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.36.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn NONSEC_WATCHDOG_IRQ();
    fn TIMER0();
    fn DUALTIMER();
    fn MPC();
    fn GPTIMERINTR();
    fn QSPIINTR();
    fn UARTRXINTR0();
    fn GPIO0();
    fn PWMINT0();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 71] = [
    Vector { _reserved: 0 },
    Vector {
        _handler: NONSEC_WATCHDOG_IRQ,
    },
    Vector { _reserved: 0 },
    Vector { _handler: TIMER0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: DUALTIMER,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: MPC },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: GPTIMERINTR,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: QSPIINTR },
    Vector {
        _handler: UARTRXINTR0,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: GPIO0 },
    Vector { _reserved: 0 },
    Vector { _handler: PWMINT0 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "1 - Non-Secure Watchdog Interrupt"]
    NONSEC_WATCHDOG_IRQ = 1,
    #[doc = "3 - Timer 0"]
    TIMER0 = 3,
    #[doc = "5 - Dual Timer"]
    DUALTIMER = 5,
    #[doc = "9 - MPC Combined"]
    MPC = 9,
    #[doc = "33 - General-Purpose Timer interrupt"]
    GPTIMERINTR = 33,
    #[doc = "38 - QSPI interrupt"]
    QSPIINTR = 38,
    #[doc = "39 - UART0 receive FIFO interrupt"]
    UARTRXINTR0 = 39,
    #[doc = "68 - GPIO 0 combined"]
    GPIO0 = 68,
    #[doc = "70 - PWM0 interrupt"]
    PWMINT0 = 70,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "System Information"]
pub type Sysinfo = crate::Periph<sysinfo::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Sysinfo {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysinfo").finish()
    }
}
#[doc = "System Information"]
pub mod sysinfo;
#[doc = "System Information (Secure)"]
pub type SysinfoSecure = crate::Periph<sysinfo::RegisterBlock, 0x5002_0000>;
impl core::fmt::Debug for SysinfoSecure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SysinfoSecure").finish()
    }
}
#[doc = "System Information (Secure)"]
pub use self::sysinfo as sysinfo_secure;
#[doc = "System Control"]
pub type SystemControl = crate::Periph<system_control::RegisterBlock, 0x5002_1000>;
impl core::fmt::Debug for SystemControl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SystemControl").finish()
    }
}
#[doc = "System Control"]
pub mod system_control;
#[doc = "Security Attribution Unit"]
pub type Sau = crate::Periph<sau::RegisterBlock, 0xe000_edd0>;
impl core::fmt::Debug for Sau {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sau").finish()
    }
}
#[doc = "Security Attribution Unit"]
pub mod sau;
#[doc = "Timer 0"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer 0"]
pub mod timer0;
#[doc = "Dual Timer"]
pub type Dualtimer = crate::Periph<dualtimer::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Dualtimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dualtimer").finish()
    }
}
#[doc = "Dual Timer"]
pub mod dualtimer;
#[doc = "General-Purpose Timer"]
pub type Gptimer = crate::Periph<gptimer::RegisterBlock, 0x4010_c000>;
impl core::fmt::Debug for Gptimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gptimer").finish()
    }
}
#[doc = "General-Purpose Timer"]
pub mod gptimer;
#[doc = "Timer 0 (Secure)"]
pub type Timer0Secure = crate::Periph<timer0::RegisterBlock, 0x5000_0000>;
impl core::fmt::Debug for Timer0Secure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0Secure").finish()
    }
}
#[doc = "Timer 0 (Secure)"]
pub use self::timer0 as timer0_secure;
#[doc = "Dual Timer (Secure)"]
pub type DualtimerSecure = crate::Periph<dualtimer::RegisterBlock, 0x5000_2000>;
impl core::fmt::Debug for DualtimerSecure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DualtimerSecure").finish()
    }
}
#[doc = "Dual Timer (Secure)"]
pub use self::dualtimer as dualtimer_secure;
#[doc = "General-Purpose Timer (Secure)"]
pub type GptimerSecure = crate::Periph<gptimer::RegisterBlock, 0x5010_c000>;
impl core::fmt::Debug for GptimerSecure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("GptimerSecure").finish()
    }
}
#[doc = "General-Purpose Timer (Secure)"]
pub use self::gptimer as gptimer_secure;
#[doc = "General-purpose I/O 0"]
pub type Gpio0 = crate::Periph<gpio0::RegisterBlock, 0x4100_0000>;
impl core::fmt::Debug for Gpio0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0").finish()
    }
}
#[doc = "General-purpose I/O 0"]
pub mod gpio0;
#[doc = "General-purpose I/O 0 (Secure)"]
pub type Gpio0Secure = crate::Periph<gpio0::RegisterBlock, 0x5100_0000>;
impl core::fmt::Debug for Gpio0Secure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio0Secure").finish()
    }
}
#[doc = "General-purpose I/O 0 (Secure)"]
pub use self::gpio0 as gpio0_secure;
#[doc = "UART 0"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4010_5000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "UART 0"]
pub mod uart0;
#[doc = "UART 0 (Secure)"]
pub type Uart0Secure = crate::Periph<uart0::RegisterBlock, 0x5010_5000>;
impl core::fmt::Debug for Uart0Secure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0Secure").finish()
    }
}
#[doc = "UART 0 (Secure)"]
pub use self::uart0 as uart0_secure;
#[doc = "Non-secure Watchdog Timer"]
pub type Watchdog = crate::Periph<watchdog::RegisterBlock, 0x4008_1000>;
impl core::fmt::Debug for Watchdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Watchdog").finish()
    }
}
#[doc = "Non-secure Watchdog Timer"]
pub mod watchdog;
#[doc = "Cache"]
pub type ICache = crate::Periph<i_cache::RegisterBlock, 0x5001_0000>;
impl core::fmt::Debug for ICache {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ICache").finish()
    }
}
#[doc = "Cache"]
pub mod i_cache;
#[doc = "PWM_IP6512"]
pub type Pwm = crate::Periph<pwm::RegisterBlock, 0x4010_7000>;
impl core::fmt::Debug for Pwm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwm").finish()
    }
}
#[doc = "PWM_IP6512"]
pub mod pwm;
#[doc = "Watchdog (Secure)"]
pub type WatchdogSecure = crate::Periph<watchdog::RegisterBlock, 0x5008_1000>;
impl core::fmt::Debug for WatchdogSecure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("WatchdogSecure").finish()
    }
}
#[doc = "Watchdog (Secure)"]
pub use self::watchdog as watchdog_secure;
#[doc = "S32K Watchdog (Secure)"]
pub type S32kwatchdog = crate::Periph<watchdog::RegisterBlock, 0x5002_e000>;
impl core::fmt::Debug for S32kwatchdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("S32kwatchdog").finish()
    }
}
#[doc = "S32K Watchdog (Secure)"]
pub use self::watchdog as s32kwatchdog;
#[doc = "Serial Communication Controller"]
pub type Scc = crate::Periph<scc::RegisterBlock, 0x5010_b000>;
impl core::fmt::Debug for Scc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Scc").finish()
    }
}
#[doc = "Serial Communication Controller"]
pub mod scc;
#[doc = "Secure Privilege Control Block"]
pub type Spctrl = crate::Periph<spctrl::RegisterBlock, 0x5008_0000>;
impl core::fmt::Debug for Spctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spctrl").finish()
    }
}
#[doc = "Secure Privilege Control Block"]
pub mod spctrl;
#[doc = "Non-secure Privilege Control Block"]
pub type Nspctrl = crate::Periph<nspctrl::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Nspctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Nspctrl").finish()
    }
}
#[doc = "Non-secure Privilege Control Block"]
pub mod nspctrl;
#[doc = "Memory Protection Controller 0"]
pub type Sram0mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5008_3000>;
impl core::fmt::Debug for Sram0mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sram0mpc").finish()
    }
}
#[doc = "Memory Protection Controller 0"]
pub mod sram0mpc;
#[doc = "SRAM 1 Memory Protection Controller"]
pub type Sram1mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5008_4000>;
impl core::fmt::Debug for Sram1mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sram1mpc").finish()
    }
}
#[doc = "SRAM 1 Memory Protection Controller"]
pub use self::sram0mpc as sram1mpc;
#[doc = "SRAM 2 Memory Protection Controller"]
pub type Sram2mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5008_5000>;
impl core::fmt::Debug for Sram2mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sram2mpc").finish()
    }
}
#[doc = "SRAM 2 Memory Protection Controller"]
pub use self::sram0mpc as sram2mpc;
#[doc = "SRAM 3 Memory Protection Controller"]
pub type Sram3mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5008_6000>;
impl core::fmt::Debug for Sram3mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sram3mpc").finish()
    }
}
#[doc = "SRAM 3 Memory Protection Controller"]
pub use self::sram0mpc as sram3mpc;
#[doc = "Code SRAM Memory Protection Controller"]
pub type CodeSramMpc = crate::Periph<sram0mpc::RegisterBlock, 0x5210_0000>;
impl core::fmt::Debug for CodeSramMpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CodeSramMpc").finish()
    }
}
#[doc = "Code SRAM Memory Protection Controller"]
pub use self::sram0mpc as code_sram_mpc;
#[doc = "QSPI Flash Memory Protection Controller"]
pub type QspiMpc = crate::Periph<sram0mpc::RegisterBlock, 0x5200_0000>;
impl core::fmt::Debug for QspiMpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QspiMpc").finish()
    }
}
#[doc = "QSPI Flash Memory Protection Controller"]
pub use self::sram0mpc as qspi_mpc;
#[doc = "EFlash0 Memory Protection Controller"]
pub type Eflash0Mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5220_0000>;
impl core::fmt::Debug for Eflash0Mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eflash0Mpc").finish()
    }
}
#[doc = "EFlash0 Memory Protection Controller"]
pub use self::sram0mpc as eflash0_mpc;
#[doc = "EFlash1 Memory Protection Controller"]
pub type Eflash1Mpc = crate::Periph<sram0mpc::RegisterBlock, 0x5230_0000>;
impl core::fmt::Debug for Eflash1Mpc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eflash1Mpc").finish()
    }
}
#[doc = "EFlash1 Memory Protection Controller"]
pub use self::sram0mpc as eflash1_mpc;
#[doc = "QSPI Flash Controller"]
pub type Qspifctrl = crate::Periph<qspifctrl::RegisterBlock, 0x4280_0000>;
impl core::fmt::Debug for Qspifctrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspifctrl").finish()
    }
}
#[doc = "QSPI Flash Controller"]
pub mod qspifctrl;
#[doc = "QSPI Flash Controller (Secure)"]
pub type QspifctrlSecure = crate::Periph<qspifctrl::RegisterBlock, 0x5280_0000>;
impl core::fmt::Debug for QspifctrlSecure {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("QspifctrlSecure").finish()
    }
}
#[doc = "QSPI Flash Controller (Secure)"]
pub use self::qspifctrl as qspifctrl_secure;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "SYSINFO"]
    pub sysinfo: Sysinfo,
    #[doc = "SYSINFO_Secure"]
    pub sysinfo_secure: SysinfoSecure,
    #[doc = "SystemControl"]
    pub system_control: SystemControl,
    #[doc = "SAU"]
    pub sau: Sau,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "DUALTIMER"]
    pub dualtimer: Dualtimer,
    #[doc = "GPTIMER"]
    pub gptimer: Gptimer,
    #[doc = "TIMER0_Secure"]
    pub timer0_secure: Timer0Secure,
    #[doc = "DUALTIMER_Secure"]
    pub dualtimer_secure: DualtimerSecure,
    #[doc = "GPTIMER_Secure"]
    pub gptimer_secure: GptimerSecure,
    #[doc = "GPIO0"]
    pub gpio0: Gpio0,
    #[doc = "GPIO0_Secure"]
    pub gpio0_secure: Gpio0Secure,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "UART0_Secure"]
    pub uart0_secure: Uart0Secure,
    #[doc = "WATCHDOG"]
    pub watchdog: Watchdog,
    #[doc = "iCache"]
    pub i_cache: ICache,
    #[doc = "PWM"]
    pub pwm: Pwm,
    #[doc = "WATCHDOG_Secure"]
    pub watchdog_secure: WatchdogSecure,
    #[doc = "S32KWATCHDOG"]
    pub s32kwatchdog: S32kwatchdog,
    #[doc = "SCC"]
    pub scc: Scc,
    #[doc = "SPCTRL"]
    pub spctrl: Spctrl,
    #[doc = "NSPCTRL"]
    pub nspctrl: Nspctrl,
    #[doc = "SRAM0MPC"]
    pub sram0mpc: Sram0mpc,
    #[doc = "SRAM1MPC"]
    pub sram1mpc: Sram1mpc,
    #[doc = "SRAM2MPC"]
    pub sram2mpc: Sram2mpc,
    #[doc = "SRAM3MPC"]
    pub sram3mpc: Sram3mpc,
    #[doc = "CODE_SRAM_MPC"]
    pub code_sram_mpc: CodeSramMpc,
    #[doc = "QSPI_MPC"]
    pub qspi_mpc: QspiMpc,
    #[doc = "EFLASH0_MPC"]
    pub eflash0_mpc: Eflash0Mpc,
    #[doc = "EFLASH1_MPC"]
    pub eflash1_mpc: Eflash1Mpc,
    #[doc = "QSPIFCTRL"]
    pub qspifctrl: Qspifctrl,
    #[doc = "QSPIFCTRL_Secure"]
    pub qspifctrl_secure: QspifctrlSecure,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            sysinfo: Sysinfo::steal(),
            sysinfo_secure: SysinfoSecure::steal(),
            system_control: SystemControl::steal(),
            sau: Sau::steal(),
            timer0: Timer0::steal(),
            dualtimer: Dualtimer::steal(),
            gptimer: Gptimer::steal(),
            timer0_secure: Timer0Secure::steal(),
            dualtimer_secure: DualtimerSecure::steal(),
            gptimer_secure: GptimerSecure::steal(),
            gpio0: Gpio0::steal(),
            gpio0_secure: Gpio0Secure::steal(),
            uart0: Uart0::steal(),
            uart0_secure: Uart0Secure::steal(),
            watchdog: Watchdog::steal(),
            i_cache: ICache::steal(),
            pwm: Pwm::steal(),
            watchdog_secure: WatchdogSecure::steal(),
            s32kwatchdog: S32kwatchdog::steal(),
            scc: Scc::steal(),
            spctrl: Spctrl::steal(),
            nspctrl: Nspctrl::steal(),
            sram0mpc: Sram0mpc::steal(),
            sram1mpc: Sram1mpc::steal(),
            sram2mpc: Sram2mpc::steal(),
            sram3mpc: Sram3mpc::steal(),
            code_sram_mpc: CodeSramMpc::steal(),
            qspi_mpc: QspiMpc::steal(),
            eflash0_mpc: Eflash0Mpc::steal(),
            eflash1_mpc: Eflash1Mpc::steal(),
            qspifctrl: Qspifctrl::steal(),
            qspifctrl_secure: QspifctrlSecure::steal(),
        }
    }
}
